# Header
menu:
  主页: /
  所有文章: /archives
  Web端: /categories/Web
  移动端: /categories/Mobile
  #随笔: /categories/随笔

# SubNav
subnav:
  github: https://github.com/pengrun
  weibo: http://weibo.com/51200705
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  mail: pengrun_520@gmail.com
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-64245388-1'
favicon: /favicon.jpg

#你的头像url
avatar: https://avatars3.githubusercontent.com/u/2194901?v=3&s=460
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  优活智联: http://www.uiho.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 13年重庆理工大学毕业，2年iOS开发经验，目前南漂来深圳，从事车联网相关工作。
